INSERT INTO users (email, password_hash, name, role) VALUES
('admin@demo.com', '$2b$10$e4dPQpe3XIDluCZCv3b3iu/H/3f816tgim6l5ly5k7pChHG235Dey', 'Admin User', 'admin')
ON CONFLICT (email) DO NOTHING;

INSERT INTO suppliers (name, country, tier, city, capabilities, capacity_utilization, export_controlled, revenue_billions, employees, founded_year, certifications, status) VALUES
('TSMC', 'Taiwan', 1, 'Hsinchu', 'Logic foundry: 2nm, 3nm, 5nm, 7nm, EUV lithography, advanced packaging CoWoS', 95.5, false, 92.0, 73000, 1987, 'ISO9001, IATF16949, AEC-Q100', 'active'),
('Samsung Foundry', 'South Korea', 1, 'Seoul', 'Logic foundry: 3nm GAA, 4nm, 5nm, 7nm, HBM memory, DRAM, NAND flash', 88.0, false, 74.0, 270000, 1969, 'ISO9001, ISO14001, IATF16949', 'active'),
('Intel Foundry', 'USA', 1, 'Santa Clara', 'Logic foundry: Intel 18A, Intel 3, Intel 4, x86 microprocessors, advanced packaging', 72.0, false, 54.2, 110000, 1968, 'ISO9001, IATF16949, DoD trusted foundry', 'active'),
('ASML', 'Netherlands', 1, 'Veldhoven', 'EUV lithography systems, DUV immersion, metrology equipment - monopoly on EUV', 99.0, true, 21.3, 43000, 1984, 'ISO9001, SEMI standards', 'active'),
('Lam Research', 'USA', 1, 'Fremont', 'Etch equipment, deposition (CVD, ALD, PVD), clean equipment for advanced nodes', 85.0, false, 17.4, 17000, 1980, 'ISO9001, SEMI standards', 'active'),
('Applied Materials', 'USA', 1, 'Santa Clara', 'Deposition, etch, CMP, thermal, inspection equipment for all semiconductor processes', 87.0, false, 26.5, 34000, 1967, 'ISO9001, ISO14001', 'active'),
('KLA Corporation', 'USA', 1, 'Milpitas', 'Inspection, metrology, process control equipment - critical for yield management', 91.0, false, 10.5, 14000, 1975, 'ISO9001, SEMI standards', 'active'),
('SK Hynix', 'South Korea', 1, 'Icheon', 'DRAM, HBM3/HBM3e, NAND flash, enterprise SSD - #2 DRAM market globally', 89.0, false, 25.1, 30000, 1983, 'ISO9001, AEC-Q100', 'active'),
('Micron Technology', 'USA', 1, 'Boise', 'DRAM, HBM, NAND flash, enterprise SSD - only US-based DRAM manufacturer', 84.0, false, 15.5, 40000, 1978, 'ISO9001, IATF16949', 'active'),
('Shin-Etsu Chemical', 'Japan', 2, 'Tokyo', 'Silicon wafers 300mm/200mm, photoresist, silicones - largest silicon wafer producer', 93.0, false, 18.2, 36000, 1926, 'ISO9001, ISO14001', 'active'),
('Tokyo Electron (TEL)', 'Japan', 1, 'Tokyo', 'Coater/developers, thermal processing, etch systems, deposition equipment', 88.0, true, 17.8, 15000, 1963, 'ISO9001, SEMI standards', 'active'),
('Entegris', 'USA', 2, 'Billerica', 'Advanced materials: CMP slurry, ultra-pure chemicals, filtration, gas purification', 82.0, false, 3.7, 9500, 1966, 'ISO9001, ISO14001', 'active'),
('Synopsys', 'USA', 2, 'Mountain View', 'EDA software: synthesis, simulation, verification, IP cores for chip design', 96.0, true, 5.8, 20000, 1986, 'ISO9001, DoD trusted EDA', 'active'),
('Cadence Design Systems', 'USA', 2, 'San Jose', 'EDA software: place & route, custom design, verification, PCB design tools', 94.0, true, 3.9, 11000, 1988, 'ISO9001, DoD trusted EDA', 'active'),
('NVIDIA', 'USA', 1, 'Santa Clara', 'GPU design, AI accelerators, networking (as design partner/major customer)', 98.0, true, 44.9, 29600, 1993, 'ISO9001, ISO14001', 'active')
ON CONFLICT DO NOTHING;

INSERT INTO components (name, type, process_node_nm, supplier_id, lead_time_weeks, allocated_to, status, monthly_capacity_k_units, current_allocation_pct, price_usd, criticality) VALUES
('HBM3 Memory', 'memory', 5, 8, 52, 'NVIDIA, AMD, Intel', 'constrained', 180, 98.5, 2800, 'critical'),
('HBM3e Memory', 'memory', 5, 2, 48, 'NVIDIA H200, AMD MI300X', 'constrained', 120, 99.2, 3400, 'critical'),
('CoWoS-S Advanced Packaging', 'packaging', NULL, 1, 36, 'NVIDIA H100/H200, AMD', 'constrained', 85, 97.8, 800, 'critical'),
('EUV Mask Set (5nm)', 'mask', 5, 1, 24, 'Apple A18, Qualcomm X70', 'available', 200, 82.0, 1200, 'high'),
('3nm Logic Wafers', 'logic_chip', 3, 1, 52, 'Apple A17 Pro, Apple M4', 'allocated', 45, 95.5, 18000, 'critical'),
('5nm Logic Wafers', 'logic_chip', 5, 1, 48, 'NVIDIA, AMD, Qualcomm, Apple', 'constrained', 120, 94.2, 12000, 'critical'),
('EUV Lithography System', 'equipment', NULL, 4, 104, 'TSMC, Samsung, Intel', 'allocated', 5, 100.0, 180000000, 'critical'),
('Advanced Substrate (FC-BGA)', 'substrate', NULL, 10, 40, 'Intel, NVIDIA, AMD', 'constrained', 450, 91.0, 380, 'high'),
('CMP Slurry (Advanced)', 'chemical', NULL, 12, 8, 'All fabs', 'available', 5000, 72.0, 45, 'medium'),
('KrF Photoresist', 'chemical', NULL, 10, 6, 'All fabs 200mm', 'available', 8000, 65.0, 28, 'low'),
('EUV Photoresist', 'chemical', NULL, 10, 12, 'TSMC, Samsung EUV', 'constrained', 1200, 88.0, 380, 'high'),
('Ion Implanter (Advanced)', 'equipment', NULL, 5, 52, 'TSMC, Samsung Foundry', 'allocated', 12, 95.0, 2500000, 'high'),
('300mm Silicon Wafers', 'substrate', NULL, 10, 16, 'All leading fabs', 'available', 12000, 87.5, 125, 'high'),
('DRAM DDR5 16Gb', 'memory', 10, 9, 26, 'PC/server manufacturers', 'available', 28000, 78.0, 8, 'medium'),
('CoW-on-SoIC Packaging', 'packaging', NULL, 1, 52, 'Apple, MediaTek (next-gen)', 'constrained', 25, 96.0, 1500, 'critical')
ON CONFLICT DO NOTHING;

INSERT INTO allocations (component_id, customer, quantity_k_units, priority, locked_until, status, contract_value_millions, notes) VALUES
(3, 'NVIDIA', 40, 1, CURRENT_DATE + 365, 'confirmed', 3200, 'Locked for H100/H200 production through 2025. Executive-level agreement.'),
(3, 'AMD', 15, 2, CURRENT_DATE + 270, 'confirmed', 1200, 'MI300X production allocation. Renewable quarterly.'),
(5, 'Apple Inc.', 18, 1, CURRENT_DATE + 365, 'confirmed', 8100, 'A18 Pro and M4 chip production locked through 2025.'),
(6, 'NVIDIA', 45, 1, CURRENT_DATE + 180, 'confirmed', 5400, 'H100 production. Critical path for data center revenue.'),
(6, 'Qualcomm', 28, 2, CURRENT_DATE + 180, 'confirmed', 3360, 'Snapdragon X Elite and X Plus series.'),
(6, 'Apple Inc.', 25, 1, CURRENT_DATE + 270, 'confirmed', 3000, 'A17 and M-series chips, secured capacity.'),
(1, 'NVIDIA', 90, 1, CURRENT_DATE + 365, 'confirmed', 25200, 'H200/Blackwell GB200 training cluster memory.'),
(1, 'AMD', 45, 2, CURRENT_DATE + 270, 'confirmed', 12600, 'Instinct MI300X memory allocation.'),
(1, 'Google', 25, 2, CURRENT_DATE + 180, 'confirmed', 7000, 'TPUv5 memory, datacenter AI infrastructure.'),
(2, 'NVIDIA', 60, 1, CURRENT_DATE + 365, 'confirmed', 20400, 'Next-gen Blackwell B200 HBM3e requirement.'),
(7, 'TSMC', 2, 1, CURRENT_DATE + 730, 'confirmed', 360000, 'N3/N2 capacity expansion - 2 EUV systems per year.'),
(7, 'Samsung', 1, 2, CURRENT_DATE + 365, 'confirmed', 180000, '3nm GAA production expansion.'),
(8, 'NVIDIA', 180, 1, CURRENT_DATE + 270, 'confirmed', 684, 'FC-BGA substrates for GPU packages.'),
(13, 'TSMC Taiwan', 6000, 1, CURRENT_DATE + 90, 'confirmed', 750, 'Advanced node 300mm wafer supply agreement.'),
(15, 'Apple', 12, 1, CURRENT_DATE + 365, 'provisional', 1800, 'Next-gen SoIC packaging for M5 chip (unconfirmed).')
ON CONFLICT DO NOTHING;

INSERT INTO risk_alerts (component_id, supplier_id, risk_type, severity, title, description, impact, mitigation, status) VALUES
(7, 4, 'single_source', 'critical', 'ASML EUV Monopoly - No Alternative Supplier', 'ASML is the sole global supplier of EUV lithography systems. No alternative exists for sub-7nm chip production. 104-week lead time creates extreme vulnerability.', 'Any ASML disruption halts all leading-edge chip production globally. TSMC, Samsung, Intel would be unable to produce advanced chips within 2 years.', 'Maintain strategic reserve of 2+ EUV systems. Lobby for ASML production expansion. Investigate e-beam lithography as 10+ year alternative.', 'monitoring'),
(1, 8, 'capacity', 'critical', 'HBM3 Shortage - AI Demand Exceeds Supply 400%', 'AI accelerator demand for HBM3 memory has grown 4x faster than production capacity. SK Hynix and Micron are sold out through 2026.', 'NVIDIA H100/H200, AMD MI300X, and Google TPU production constrained. Data center expansion delayed by 6-12 months. $50B+ in stranded demand.', 'Lock multi-year contracts immediately. Invest in Micron capacity expansion ($2B commitment). Explore Samsung as secondary HBM supplier.', 'open'),
(5, 1, 'geopolitical', 'critical', 'Taiwan Geopolitical Risk - TSMC 3nm Single Source', 'TSMC controls 90%+ of sub-5nm chip production capacity. All located in Taiwan, subject to cross-strait tensions. Potential for rapid disruption with no fallback.', 'Loss of TSMC access would halt production of all Apple chips, most NVIDIA GPUs, Qualcomm, MediaTek chips. Estimated $500B+ annual impact to global tech industry.', 'Accelerate TSMC Arizona Fab 21 ramp. Qualify Samsung Foundry as alternative for select products. Support Intel IFS as long-term US domestic alternative.', 'monitoring'),
(NULL, 4, 'export_control', 'high', 'ASML EUV Export Controls to China', 'US/Netherlands export controls prohibit ASML EUV system sales to China. China SMIC limited to 7nm+ nodes. Risk of Chinese retaliation impacting rare earth supply.', 'China cannot access leading-edge chips. Risk of retaliatory export controls on rare earth metals (gallium, germanium) critical for semiconductor manufacturing.', 'Diversify rare earth supply. Build strategic reserves of gallium, germanium. Develop alternative compound semiconductor sources.', 'monitoring'),
(3, 1, 'capacity', 'high', 'CoWoS Packaging Bottleneck at TSMC', 'TSMC CoWoS advanced packaging capacity is severely constrained. NVIDIA H100/H200 production limited by packaging, not wafer supply.', 'NVIDIA cannot ship all ordered H100/H200 GPUs despite having wafers. AMD MI300X also affected. $5B+ quarterly revenue impact to NVIDIA.', 'TSMC expanding CoWoS capacity +60% by Q4 2025. Evaluate ASE, SPIL as alternative packaging partners. Consider in-house assembly.', 'mitigating'),
(NULL, 10, 'single_source', 'high', 'Shin-Etsu 300mm Silicon Wafer Dependency', 'Shin-Etsu + SUMCO control 60% of 300mm silicon wafer supply. Japanese export controls could disrupt supply. Wafer demand growing with AI fab expansion.', 'Wafer shortage would constrain production at all leading fabs. 16-week lead times with no short-term alternatives.', 'Qualify Siltronic (Germany) and SK Siltron (Korea) as additional wafer suppliers. Build 8-week strategic buffer inventory.', 'open'),
(NULL, 13, 'export_control', 'high', 'Synopsys/Cadence EDA Export Controls Risk', 'US EDA tools (Synopsys, Cadence) are subject to export controls. Any restrictions would prevent chip designers from using these tools. China developing alternatives.', 'Chinese chip design companies would lose access to leading EDA tools. However, US companies also face risk if China restricts access to foundries.', 'Maintain offline license backup systems. Evaluate open-source EDA alternatives for resilience.', 'monitoring'),
(2, 2, 'capacity', 'high', 'HBM3e Supply Severely Constrained Through 2026', 'Samsung and SK Hynix HBM3e capacity is 100% allocated to NVIDIA for Blackwell GPUs. No spot market availability.', 'Any new AI accelerator program cannot source HBM3e memory. AMD MI400, Google TPUv6 face memory supply risk.', 'Place 18-month advance orders with both Samsung and SK Hynix. Include penalty clauses for non-delivery. Begin Micron qualification for HBM3e.', 'open'),
(NULL, 9, 'natural_disaster', 'medium', 'Micron Boise Facility Earthquake Risk', 'Microns headquarters and primary DRAM fab in Boise, Idaho is in seismically active zone. A major earthquake could disrupt 25% of US DRAM production.', 'Loss of Boise facility would reduce US DRAM supply by 25% for 12-18 months. DRAM prices would spike 50-100%.', 'Ensure Micron Singapore and Japan fabs can absorb production. Build 6-week DRAM buffer inventory. Qualify Samsung and Hynix as dual sources.', 'monitoring'),
(6, 1, 'capacity', 'medium', 'TSMC 5nm Allocation Oversubscribed', 'Demand for TSMC 5nm capacity exceeds supply by 35%. Multiple customers competing: NVIDIA, Qualcomm, Apple, AMD, MediaTek.', 'Lower-priority customers will face allocation cuts. Qualcomm and MediaTek most at risk as Apple and NVIDIA have priority contracts.', 'Negotiate multi-year capacity reservations. Pay capacity reservation fees upfront. Qualify Samsung 4nm as fallback.', 'mitigating'),
(NULL, 12, 'financial', 'medium', 'Entegris Supply Chain Concentration Risk', 'Entegris acquired CMC Materials (2023), creating concentration in advanced process chemicals. Single supplier for many critical CMP formulations.', 'Any quality or supply issue at Entegris could halt production at multiple fabs simultaneously. Limited qualified alternatives for advanced CMP slurries.', 'Qualify Versum Materials and Fujifilm as alternative CMP suppliers. Build 12-week buffer inventory of critical chemicals.', 'open'),
(NULL, 11, 'export_control', 'medium', 'Tokyo Electron Export Controls Expansion Risk', 'US pressure on Japan to expand semiconductor equipment export controls to China. TEL has significant China revenue exposure (30%+ of sales).', 'TEL compliance costs and potential China market loss could reduce R&D investment, slowing equipment advancement. Could also cause supply prioritization issues.', 'Maintain dual-source strategy for etch and deposition equipment. Accelerate Lam Research and Applied Materials qualification as alternatives.', 'monitoring'),
(4, 1, 'capacity', 'low', 'EUV Mask Supply Lead Times Extending', 'Advanced EUV mask supply lead times increasing from 16 to 24 weeks due to mask blank shortage and defect inspection capacity limits.', 'New tape-outs and process development cycles extended. Affects time-to-market for new chip designs.', 'Build 8-week mask buffer for critical production programs. Qualify second mask supplier for non-critical masks.', 'monitoring'),
(13, 10, 'capacity', 'low', '300mm Wafer Supply Tightening Q3 2025', 'Growing fab capacity additions (Intel, TSMC Arizona, Samsung Texas) absorbing available 300mm wafer supply. Spot prices rising.', 'Non-contracted wafer purchases face 20-30% price premium. Small fabs without LTAs at risk.', 'Ensure long-term agreements cover 110% of baseline demand. Lock in Q3-Q4 2025 supply now.', 'open'),
(9, 12, 'technology', 'low', 'CMP Slurry Formulation for 2nm Nodes Delayed', 'Next-generation CMP slurry formulations for 2nm and below process nodes behind schedule. Current formulas may not meet planarization requirements.', 'Could delay TSMC N2 yield ramp by 1-2 quarters if not resolved. Impact to Apple M5 and NVIDIA next-gen GPU timeline.', 'Engage Entegris, Versum, and Fujifilm simultaneously on 2nm CMP development. Fund joint development program.', 'open')
ON CONFLICT DO NOTHING;

INSERT INTO fabs (name, operator, location, country, process_nodes, monthly_capacity_kwafers, utilization_pct, status, construction_cost_billions, opened_year, customers) VALUES
('Fab 18 (N3/N2)', 'TSMC', 'Tainan, Taiwan', 'Taiwan', '3nm, 2nm', 55, 95.0, 'operational', 20.0, 2022, 'Apple, NVIDIA, AMD, Qualcomm'),
('Fab 21 Phase 1 (N4)', 'TSMC', 'Phoenix, Arizona', 'USA', '4nm', 20, 65.0, 'operational', 12.0, 2024, 'Apple, NVIDIA, AMD'),
('Fab 21 Phase 2 (N3/N2)', 'TSMC', 'Phoenix, Arizona', 'USA', '3nm, 2nm', 0, 0.0, 'construction', 12.0, 2028, 'TBD'),
('S3 Fab (3nm GAA)', 'Samsung', 'Hwaseong, South Korea', 'South Korea', '3nm GAA, 4nm', 40, 78.0, 'operational', 15.0, 2023, 'Qualcomm, NVIDIA, IBM'),
('Taylor Fab', 'Samsung', 'Taylor, Texas', 'USA', '4nm, 2nm', 0, 0.0, 'construction', 17.0, 2026, 'TBD'),
('Fab 34 (Intel 3)', 'Intel', 'Leixlip, Ireland', 'Ireland', 'Intel 3, Intel 4', 25, 72.0, 'operational', 18.0, 2023, 'Intel products, Microsoft'),
('Fab 52/62 (Intel 18A)', 'Intel', 'Chandler, Arizona', 'USA', 'Intel 18A, Intel 3', 15, 45.0, 'expansion', 28.0, 2025, 'Amazon, Qualcomm (planned)'),
('P1K/P1T (HBM3e)', 'SK Hynix', 'Icheon, South Korea', 'South Korea', 'HBM3e, DRAM 1beta', 80, 98.0, 'operational', 8.0, 2023, 'NVIDIA, AMD, Google'),
('Manassas Fab', 'Micron', 'Manassas, Virginia', 'USA', 'DRAM 1alpha, 1beta', 35, 84.0, 'operational', 3.0, 2012, 'Enterprise, PC OEMs'),
('New Memory Campus', 'Micron', 'Boise, Idaho', 'USA', 'DRAM HBM, NAND', 0, 0.0, 'planned', 15.0, 2027, 'AI/HPC customers')
ON CONFLICT DO NOTHING;

INSERT INTO market_intelligence (title, topic, summary, impact_level, source, published_date, affected_components, analyst, action_items) VALUES
('NVIDIA Blackwell Demand Exceeds 2025 Supply Capacity', 'demand', 'NVIDIA Blackwell B200 and GB200 systems are oversold for 2025 with demand exceeding supply 3:1. CoWoS packaging and HBM3e remain bottlenecks. Hyperscalers (Microsoft, Google, AWS, Meta) have locked up capacity through contract minimums.', 'high', 'Semiconductor Digest', CURRENT_DATE - 5, 'CoWoS-S packaging, HBM3e, 5nm wafers', 'Sarah Chen', 'Lock HBM3e allocation now; evaluate CoWoS capacity expansion investment'),
('ASML EUV Backlog Reaches 2-Year High', 'supply', 'ASML EUV system backlog now stands at 40+ systems representing $7B+ in orders. Lead times extended to 24 months. TSMC and Samsung competing for priority delivery slots. ASML cannot increase production meaningfully in short term.', 'high', 'SEMI Industry Report', CURRENT_DATE - 12, 'EUV Lithography System', 'Michael Torres', 'Confirm ASML delivery schedule; evaluate impact to fab expansion timeline'),
('China Rare Earth Export Restrictions Escalate', 'geopolitics', 'China announced expanded export controls on gallium, germanium, and antimony - critical materials for compound semiconductors and chip manufacturing. Affects LED, power electronics, and RF components. US building strategic reserves.', 'high', 'Reuters', CURRENT_DATE - 3, 'All compound semiconductor components', 'Jennifer Park', 'Assess gallium/germanium exposure; build 6-month strategic reserve; qualify alternative sources'),
('TSMC Arizona Fab 21 Yield Improvement Accelerating', 'technology', 'TSMC Arizona Fab 21 Phase 1 yield rates improving ahead of schedule, now at 85% of Taiwan fab levels. TSMC expects parity by Q2 2025. This supports US domestic production ramp for Apple M4 and NVIDIA chips.', 'medium', 'TSMC Investor Day', CURRENT_DATE - 20, '4nm wafers, Apple chips, NVIDIA GPUs', 'Robert Kim', 'Update Arizona supply contribution model; increase Q3 2025 allocations from Arizona'),
('HBM Memory Market Will Remain Undersupplied Through 2026', 'supply', 'IDC and Gartner both forecast HBM memory demand will exceed supply by 35-45% through end of 2026. SK Hynix, Samsung, and Micron are all expanding HBM capacity but cannot meet AI accelerator demand growth.', 'high', 'IDC Market Report', CURRENT_DATE - 8, 'HBM3 Memory, HBM3e Memory', 'Lisa Wang', 'Secure 24-month HBM contracts; pay reservation fees; consider equity investment in Micron capacity'),
('Intel 18A Process Technology Validation Progress', 'technology', 'Intel 18A (1.8nm class) process node achieving competitive density and performance metrics. Key customer Qualcomm proceeding with test chips. If successful, Intel Foundry becomes credible TSMC alternative by 2026.', 'medium', 'Intel Foundry Update', CURRENT_DATE - 15, '18A logic wafers', 'David Martinez', 'Monitor Intel 18A yield data; evaluate as TSMC diversification option for 2026+'),
('Samsung GAA 3nm Yield Improving, Closing Gap with TSMC', 'technology', 'Samsung 3nm GAA process node yield rates have improved to within 15% of TSMC N3E. Several customers qualifying Samsung as secondary foundry. This could provide meaningful TSMC diversification within 12-18 months.', 'medium', 'EE Times', CURRENT_DATE - 25, '3nm logic wafers', 'Emily Davis', 'Accelerate Samsung 3nm qualification; target 20% of 3nm allocation to Samsung by Q4 2025'),
('Advanced Packaging Capacity Expansion Not Keeping Pace', 'capacity', 'CoWoS, SoIC, and HBM packaging capacity globally insufficient to support AI chip volume. TSMC, ASE, and Amkor all running at 95-100% utilization. Packaging is now the primary bottleneck for AI accelerator production, not wafers.', 'high', 'McKinsey Semiconductor Report', CURRENT_DATE - 18, 'CoWoS-S packaging, SoIC packaging', 'Carlos Rodriguez', 'Evaluate packaging JV with ASE; fund TSMC CoWoS expansion; qualify SPIL as alternative'),
('US CHIPS Act Funding Accelerating Domestic Fab Construction', 'regulation', 'CHIPS Act $52B allocated: Intel ($8.5B), TSMC ($6.6B), Samsung ($6.4B), Micron ($6.1B) receiving grants. US domestic advanced chip capacity to grow from 0% to 20% of leading-edge by 2030.', 'medium', 'US Department of Commerce', CURRENT_DATE - 30, '3nm/5nm wafers, DRAM, packaging', 'Patricia Lee', 'Track fab construction milestones; update 2027 domestic supply model'),
('Photoresist Supply Chain for EUV Nodes Tightening', 'supply', 'EUV photoresist supply from JSR, TOK, and Shin-Etsu cannot keep pace with demand. Japan export controls add procurement complexity. Lead times extending from 12 to 20 weeks at some grades.', 'medium', 'Chemical Week', CURRENT_DATE - 10, 'EUV Photoresist', 'Thomas Garcia', 'Increase EUV photoresist buffer to 20 weeks; qualify second supplier; engage Japan Ministry of Economy on export license'),
('AI Data Center Power Constraints Slowing Chip Deployment', 'demand', 'Data center power availability is becoming the binding constraint on AI chip deployment. Microsoft, Google, Meta building nuclear and renewable capacity. Short-term: demand moderation for chips; long-term: accelerated infrastructure build.', 'medium', 'Data Center Dynamics', CURRENT_DATE - 7, 'HBM3 Memory, CoWoS packaging, NVIDIA GPUs', 'Kevin Brown', 'Monitor hyperscaler power capacity announcements; adjust 2025 demand forecast'),
('Specialty Chemical Export Controls Expanding', 'regulation', 'BIS expanding export controls to cover additional semiconductor process chemicals including certain etchants, precursors, and cleaning agents. Compliance costs rising for global supply chain.', 'low', 'BIS Federal Register', CURRENT_DATE - 40, 'CMP Slurry, EUV Photoresist', 'Sandra Thompson', 'Review chemical supply chain for new EAR classification; ensure export license compliance'),
('300mm Silicon Wafer Demand to Exceed Supply Q2 2025', 'supply', 'Growing fab startups and expansion programs increasing 300mm wafer demand ahead of Shin-Etsu/SUMCO capacity additions. Wafer prices expected to rise 10-15% in H1 2025.', 'medium', 'IC Insights', CURRENT_DATE - 22, '300mm Silicon Wafers', 'Amy Johnson', 'Lock Q1-Q4 2025 wafer contracts immediately; build 6-week buffer inventory'),
('Samsung HBM3e Qualification at Major AI Customers Progressing', 'technology', 'Samsung HBM3e qualification at Google TPUv5 and AMD MI400 on track. This creates a second source for HBM3e beyond SK Hynix, reducing supply concentration risk for AI memory.', 'medium', 'Samsung Semiconductor', CURRENT_DATE - 35, 'HBM3e Memory', 'Marcus Chen', 'Accelerate Samsung HBM3e qualification process; target 30% Samsung / 70% SK Hynix split by Q3 2025'),
('Geopolitical Tension Triggers Chip Stockpiling by Tech Giants', 'geopolitics', 'Apple, NVIDIA, Qualcomm, and Samsung all building strategic chip and component inventories above normal levels due to geopolitical uncertainty. This is temporarily tightening supply beyond actual demand.', 'high', 'Wall Street Journal', CURRENT_DATE - 1, 'All critical components', 'Rachel Kim', 'Assess our own stockpile strategy; ensure we are not disadvantaged vs competitors; target 8-week buffer for critical items')
ON CONFLICT DO NOTHING;
