import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Boxes, ClipboardCheck, Database, RefreshCw, Route } from 'lucide-react';
import { api } from '../api';

type Dashboard = { counts: Record<string, number>; sources: any[]; lots: any[]; workOrders: any[]; exceptions: any[]; plans: any[] };
const seedEnvelope = JSON.stringify({ sourceSystem: 'erp', sourceRecordId: 'replace-with-source-id', eventType: 'INVENTORY_RECEIPT', sourceTimestamp: new Date().toISOString(), payload: { lotCode: 'LOT-001', partNumber: 'CHIP-001', externalSupplierKey: 'SUP-001', quantity: 100, unit: 'EA' } }, null, 2);
const card = 'rounded-xl border border-slate-800 bg-slate-900 p-4';

export default function TraceabilityPage() {
  const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [envelope, setEnvelope] = useState(seedEnvelope); const [planningKey, setPlanningKey] = useState('');
  const load = useCallback(async () => { try { setError(''); setData(await api.traceability.dashboard()); } catch (e) { setError((e as Error).message); } }, []);
  useEffect(() => { void load(); }, [load]);
  const act = async (fn: () => Promise<unknown>) => { setBusy(true); setError(''); try { await fn(); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const createPlan = () => act(async () => { if (!planningKey.trim()) throw new Error('A unique planning key is required'); await api.traceability.createPlan(planningKey.trim()); setPlanningKey(''); });
  return <div className="space-y-6">
    <div className="flex items-end justify-between" id="trace-overview"><div><h1 className="text-2xl font-semibold">Lot traceability and allocation</h1><p className="mt-1 text-sm text-slate-400">All operational records come from bound authoritative sources. Human decisions and rollbacks remain auditable.</p></div><button onClick={() => void load()} className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm"><RefreshCw className="h-4 w-4" />Refresh</button></div>
    {error && <div className="rounded-lg border border-red-900 bg-red-950/50 p-3 text-sm text-red-300">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-5">{[['Parts','parts',Boxes],['Suppliers','suppliers',Database],['Lots','lots',ClipboardCheck],['Work orders','work_orders',Route],['Open exceptions','open_exceptions',AlertTriangle]].map(([label,key,Icon]: any) => <div className={card} key={key}><Icon className="mb-3 h-5 w-5 text-amber-400"/><div className="text-2xl font-semibold">{data?.counts[key] ?? '—'}</div><div className="text-xs text-slate-400">{label}</div></div>)}</div>

    <div className="grid gap-6 lg:grid-cols-2">
      <section className={card} id="trace-ingest"><h2 className="font-semibold">Ingest a signed-in integration event</h2><p className="mb-3 mt-1 text-xs text-slate-400">The source system must be authorized for the event domain. Source record IDs are idempotency keys.</p><textarea value={envelope} onChange={e => setEnvelope(e.target.value)} className="h-72 w-full rounded-lg border border-slate-700 bg-slate-950 p-3 font-mono text-xs"/><button disabled={busy} onClick={() => act(() => api.traceability.ingest(JSON.parse(envelope)))} className="mt-3 rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">Submit source event</button></section>
      <section className={card} id="trace-plan"><h2 className="font-semibold">Generate deterministic plan</h2><p className="mb-3 mt-1 text-xs text-slate-400">FIFO released lots only; approved BOM units and safety stock are hard constraints.</p><div className="flex gap-2"><input value={planningKey} onChange={e => setPlanningKey(e.target.value)} placeholder="Unique planning key" className="flex-1 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><button disabled={busy} onClick={createPlan} className="rounded-lg bg-amber-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">Run plan</button></div>
        <div className="mt-5 space-y-3">{data?.plans.map(plan => <div key={plan.id} className="rounded-lg border border-slate-800 p-3 text-sm"><div className="flex justify-between"><span className="font-mono">{plan.planning_key}</span><span className={plan.has_shortage ? 'text-red-300' : 'text-emerald-300'}>{plan.status}{plan.has_shortage ? ' · shortage' : ''}</span></div>{plan.status === 'DRAFT' && <button disabled={busy} onClick={() => act(() => api.traceability.approvePlan(plan.id,{ clientDecisionId: crypto.randomUUID(), reason: 'Planner reviewed deterministic constraints', acceptShortage: false, excludePlanLineIds: [] }))} className="mt-2 text-xs text-amber-300">Approve without shortage</button>}{['APPROVED','NEEDS_REPLAN'].includes(plan.status) && <button disabled={busy} onClick={() => act(() => api.traceability.rollbackPlan(plan.id,'Inventory or demand changed; release reservations and replan'))} className="mt-2 text-xs text-red-300">Rollback reservations</button>}</div>)}</div>
      </section>
    </div>

    <section className={card} id="trace-sources"><h2 className="mb-3 font-semibold">Authoritative source freshness</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-500"><tr><th>Domain</th><th>Source</th><th>Latest source time</th><th>Events</th><th>Rejected</th></tr></thead><tbody>{data?.sources.map(source => <tr className="border-t border-slate-800" key={`${source.source_system}-${source.domain}`}><td className="py-2">{source.domain}</td><td>{source.source_system}</td><td>{new Date(source.latest_source_timestamp).toLocaleString()}</td><td>{source.events}</td><td>{source.rejected}</td></tr>)}</tbody></table></div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section className={card} id="trace-lots"><h2 className="mb-3 font-semibold">Lots</h2><div className="space-y-2">{data?.lots.map(lot => <div key={lot.id} className="flex justify-between border-t border-slate-800 py-2 text-sm"><span><span className="font-mono">{lot.lot_code}</span> · {lot.part_number}</span><span>{lot.state} · {Number(lot.quantity_received)-Number(lot.quantity_reserved)-Number(lot.quantity_consumed)} {lot.unit} free</span></div>)}</div></section><section className={card} id="trace-exceptions"><h2 className="mb-3 font-semibold">Exceptions requiring human review</h2><div className="space-y-2">{data?.exceptions.map(item => <div key={item.id} className="border-t border-slate-800 py-2 text-sm"><div className="flex justify-between"><span>{item.exception_type} · {item.severity}</span><span>{item.state}</span></div><p className="text-xs text-slate-400">{item.reason}</p>{['OPEN','UNDER_REVIEW'].includes(item.state) && <button disabled={busy} onClick={() => act(() => api.traceability.decideException(item.id,{decision:'APPROVE',clientDecisionId:crypto.randomUUID(),rationale:'Reviewed against source evidence'}))} className="mt-1 text-xs text-amber-300">Record approval</button>}</div>)}</div></section></div>
  </div>;
}
